import fs from 'node:fs';
import path from 'node:path';
import { PrismaClient } from '@prisma/client';

export const prisma = new PrismaClient();
export const outDir = path.resolve(process.cwd(), '..', '..', 'docs', 'qa', 'recipes', 'recipe-trust-batch03');

export type Rule = { scope: 'A' | 'B'; slug: string; titleFa: string; must: string[][]; exactBlocker: string };

export const rules: Rule[] = [
  { scope: 'A', slug: 'ghanbar-polo-shirazi', titleFa: 'قنبرپلو شیرازی', must: [['rice', 'برنج'], ['ground', 'meatball', 'چرخ', 'قلقلی'], ['walnut', 'گردو'], ['raisins', 'کشمش'], ['pomegranate_molasses', 'pomegranate_paste', 'رب انار'], ['onion', 'پیاز'], ['shiraz', 'شیراز']], exactBlocker: 'قنبرپلو باید برنج، گوشت قلقلی/چرخ‌کرده، گردو، کشمش، رب انار، پیاز و هویت شیرازی داشته باشد.' },
  { scope: 'A', slug: 'vavishka', titleFa: 'واویشکا', must: [['ground', 'چرخ', 'meat', 'گوشت'], ['onion', 'پیاز'], ['tomato', 'گوجه'], ['egg', 'تخم'], ['turmeric', 'pepper', 'زردچوبه', 'فلفل'], ['gilan', 'north', 'گیلان', 'شمال']], exactBlocker: 'واویشکا استاندارد خانگی باید گوشت چرخ‌کرده، پیاز، گوجه/رب، تخم‌مرغ، ادویه و هویت شمالی داشته باشد.' },
  { scope: 'B', slug: 'eshkeneh', titleFa: 'اشکنه', must: [['onion', 'پیاز'], ['egg', 'تخم'], ['water', 'آب'], ['turmeric', 'زردچوبه'], ['salt', 'pepper', 'نمک', 'فلفل']], exactBlocker: 'اشکنه باید پیاز، تخم‌مرغ، آب/آبگوشت، زردچوبه و نمک/فلفل داشته باشد.' },
  { scope: 'B', slug: 'omelet-rob', titleFa: 'املت رب', must: [['egg', 'تخم'], ['tomato_paste', 'رب گوجه'], ['oil', 'butter', 'روغن', 'کره'], ['turmeric', 'pepper', 'salt', 'زردچوبه', 'فلفل', 'نمک']], exactBlocker: 'املت رب باید تخم‌مرغ، رب گوجه، چربی و ادویه داشته باشد.' },
  { scope: 'B', slug: 'halim-bademjan', titleFa: 'حلیم بادمجان', must: [['eggplant', 'بادمجان'], ['meat', 'گوشت'], ['kashk', 'کشک'], ['lentil', 'rice', 'عدس', 'برنج'], ['onion', 'پیاز'], ['garlic', 'سیر'], ['walnut', 'گردو'], ['mint', 'نعناع']], exactBlocker: 'حلیم بادمجان باید بادمجان، گوشت، کشک، عدس/برنج، پیاز، سیر، گردو و نعناع داشته باشد.' },
  { scope: 'B', slug: 'halim-gandom', titleFa: 'حلیم گندم', must: [['wheat', 'گندم'], ['meat', 'گوشت'], ['onion', 'پیاز'], ['water', 'آب'], ['slow', 'stretchy', 'کشدار', 'طولانی']], exactBlocker: 'حلیم گندم باید گندم، گوشت، پیاز، آب و پخت طولانی/کشدار داشته باشد.' },
  { scope: 'B', slug: 'chicken-and-mushroom', titleFa: 'خوراک مرغ و قارچ', must: [['chicken', 'مرغ'], ['mushroom', 'قارچ'], ['onion', 'garlic', 'پیاز', 'سیر'], ['salt', 'pepper', 'spice', 'نمک', 'فلفل', 'ادویه'], ['pan', 'stew', 'sauce', 'تابه', 'خوراک', 'سس']], exactBlocker: 'خوراک مرغ و قارچ باید مرغ، قارچ، پیاز/سیر، ادویه و تکنیک خوراک/تابه/سس داشته باشد.' },
  { scope: 'B', slug: 'cream-of-chicken-soup', titleFa: 'سوپ شیر', must: [['milk', 'شیر'], ['mushroom', 'chicken', 'barley', 'oat', 'قارچ', 'مرغ', 'جو'], ['flour', 'butter', 'roux', 'آرد', 'کره'], ['onion', 'carrot', 'پیاز', 'هویج']], exactBlocker: 'سوپ شیر باید شیر، ماده اصلی مثل قارچ/مرغ/جو، غلیظ‌کننده و پایه معطر داشته باشد.' },
  { scope: 'B', slug: 'gheymeh-sibzamini', titleFa: 'قیمه سیب‌زمینی', must: [['meat', 'گوشت'], ['split_pea', 'لپه'], ['tomato_paste', 'رب گوجه'], ['dried_lime', 'لیموعمانی'], ['potato', 'سیب'], ['onion', 'پیاز']], exactBlocker: 'قیمه سیب‌زمینی باید گوشت، لپه، رب، لیموعمانی، سیب‌زمینی و پیاز داشته باشد.' },
  { scope: 'B', slug: 'persian-makaroni', titleFa: 'ماکارونی ایرانی', must: [['macaroni', 'pasta', 'ماکارونی'], ['ground', 'چرخ'], ['meat', 'گوشت'], ['tomato_paste', 'رب گوجه'], ['onion', 'پیاز'], ['steam', 'dam', 'دم'], ['tahdig', 'ته دیگ']], exactBlocker: 'ماکارونی ایرانی باید پاستا، گوشت چرخ‌کرده، رب، پیاز و دم‌کردن/ته‌دیگ داشته باشد.' },
  { scope: 'B', slug: 'chelo-mahicheh', titleFa: 'چلو ماهیچه', must: [['lamb_shank', 'shank', 'ماهیچه'], ['rice', 'چلو', 'برنج'], ['onion', 'پیاز'], ['saffron', 'زعفران'], ['slow', 'braise', 'آرام']], exactBlocker: 'چلو ماهیچه باید ماهیچه، چلو/برنج، پیاز، زعفران و پخت آرام داشته باشد.' },
  { scope: 'B', slug: 'kotlet-goosht', titleFa: 'کتلت گوشت', must: [['ground', 'چرخ'], ['meat', 'گوشت'], ['potato', 'سیب زمینی', 'سیب‌زمینی'], ['onion', 'پیاز'], ['egg', 'تخم'], ['fry', 'سرخ', 'تابه']], exactBlocker: 'کتلت گوشت باید گوشت چرخ‌کرده، سیب‌زمینی، پیاز، تخم‌مرغ و سرخ‌کردن داشته باشد.' },
  { scope: 'B', slug: 'kashk-bademjan', titleFa: 'کشک بادمجان', must: [['eggplant', 'بادمجان'], ['kashk', 'کشک'], ['mint', 'نعناع'], ['onion', 'پیاز'], ['garlic', 'سیر'], ['walnut', 'گردو']], exactBlocker: 'کشک بادمجان باید بادمجان، کشک، نعناع‌داغ، پیاز، سیر و گردو داشته باشد.' },
  { scope: 'B', slug: 'kaleh-pacheh', titleFa: 'کله‌پاچه', must: [['head', 'کله'], ['trotter', 'پاچه'], ['onion', 'پیاز'], ['garlic', 'spice', 'سیر', 'ادویه'], ['slow', 'طولانی', 'آرام']], exactBlocker: 'کله‌پاچه باید کله، پاچه، پیاز، سیر/ادویه و پخت طولانی داشته باشد.' },
  { scope: 'B', slug: 'kuku-bademjan', titleFa: 'کوکو بادمجان', must: [['eggplant', 'بادمجان'], ['egg', 'تخم'], ['onion', 'garlic', 'پیاز', 'سیر'], ['turmeric', 'salt', 'pepper', 'زردچوبه', 'نمک', 'فلفل'], ['fry', 'bake', 'سرخ', 'فر']], exactBlocker: 'کوکو بادمجان باید بادمجان، تخم‌مرغ، پیاز/سیر، ادویه و پخت کوکو داشته باشد.' },
  { scope: 'B', slug: 'kuku-sabzi', titleFa: 'کوکو سبزی', must: [['herb', 'سبزی'], ['egg', 'تخم'], ['turmeric', 'salt', 'pepper', 'زردچوبه', 'نمک', 'فلفل']], exactBlocker: 'کوکو سبزی باید سبزی کوکو، تخم‌مرغ و ادویه داشته باشد.' },
  { scope: 'B', slug: 'yatimcheh', titleFa: 'یتیمچه', must: [['eggplant', 'بادمجان'], ['tomato', 'گوجه'], ['onion', 'پیاز'], ['turmeric', 'salt', 'pepper', 'زردچوبه', 'نمک', 'فلفل'], ['meatless', 'بدون گوشت', 'گیاهی']], exactBlocker: 'یتیمچه باید بادمجان، گوجه، پیاز، ادویه و هویت بدون گوشت داشته باشد.' },
  { scope: 'B', slug: 'tahandaz-morgh', titleFa: 'ته‌انداز مرغ', must: [['chicken', 'مرغ'], ['rice', 'برنج'], ['saffron', 'زعفران'], ['onion', 'پیاز'], ['bottom', 'tahdig', 'ته دیگ', 'ته‌انداز'], ['steam', 'dam', 'دم']], exactBlocker: 'ته‌انداز مرغ باید مرغ، برنج، زعفران، مزه‌دارکردن و تکنیک مرغ کف قابلمه داشته باشد.' },
  { scope: 'B', slug: 'tahchin-goosht-bademjan', titleFa: 'ته‌چین گوشت و بادمجان', must: [['rice', 'برنج'], ['yogurt', 'ماست'], ['egg', 'تخم'], ['saffron', 'زعفران'], ['meat', 'گوشت'], ['eggplant', 'بادمجان'], ['layer', 'mold', 'قالب', 'لایه']], exactBlocker: 'ته‌چین باید پایه برنج/ماست/تخم‌مرغ/زعفران و لایه گوشت و بادمجان داشته باشد.' },
  { scope: 'B', slug: 'fried-chicken', titleFa: 'مرغ سوخاری', must: [['chicken', 'مرغ'], ['flour', 'breadcrumb', 'آرد', 'پودر سوخاری'], ['seasoning', 'spice', 'ادویه'], ['fry', 'سرخ']], exactBlocker: 'مرغ سوخاری باید مرغ، پوشش آرد/سوخاری، ادویه و سرخ‌کردن داشته باشد.' },
];

export function ensureOutDir() { fs.mkdirSync(outDir, { recursive: true }); }
export function writeJson(name: string, value: unknown) { ensureOutDir(); fs.writeFileSync(path.join(outDir, name), JSON.stringify(value, null, 2), 'utf8'); }
export function writeMd(name: string, value: string) { ensureOutDir(); fs.writeFileSync(path.join(outDir, name), value, 'utf8'); }
export function getDbUrl() { return process.env.DATABASE_URL ?? ''; }
export function redactedDbUrl() { return getDbUrl().replace(/:\/\/.*@/, '://***@'); }
export function assertLocalDatabase() { const url = getDbUrl(); const lower = url.toLowerCase(); if (!(lower.includes('localhost') || lower.includes('127.0.0.1') || lower.includes('host.docker.internal')) || /(prod|production|neon|supabase|render|railway|amazonaws|rds|azure|cloudsql)/i.test(url)) throw new Error(`DATABASE_URL_NOT_LOCAL_DEV:${redactedDbUrl()}`); }
export async function getCounts() { const [totalRecipes, activePublic, draftPrivate, ingredientCount, mezePublic] = await Promise.all([prisma.recipe.count(), prisma.recipe.count({ where: { status: 'active', isPublic: true } }), prisma.recipe.count({ where: { NOT: { status: 'active', isPublic: true } } }), prisma.ingredient.count(), prisma.recipe.count({ where: { id: { startsWith: 'meze50_' }, status: 'active', isPublic: true } })]); return { totalRecipes, activePublic, draftPrivate, ingredientCount, mezePublic }; }
export function parseJson(value: unknown, fallback: any = null) { if (value == null) return fallback; if (typeof value !== 'string') return value; try { return JSON.parse(value); } catch { return fallback; } }
export function textValues(value: unknown): string { const parts: string[] = []; const walk = (v: unknown) => { if (v == null) return; if (typeof v === 'string' || typeof v === 'number' || typeof v === 'boolean') { parts.push(String(v)); return; } if (Array.isArray(v)) return v.forEach(walk); if (typeof v === 'object') Object.values(v as Record<string, unknown>).forEach(walk); }; walk(value); return parts.join(' '); }
export function recipeBlob(recipe: any) { return textValues({ title: recipe?.title, description: recipe?.description, category: recipe?.category, region: recipe?.region, categories: parseJson(recipe?.categories, []), gris: recipe?.gris, ingredients: recipe?.ingredients?.map((ri: any) => ({ name: ri.name, code: ri.ingredient?.code, nameFa: ri.ingredient?.nameFa, nameEn: ri.ingredient?.nameEn, notes: parseJson(ri.notes, ri.notes) })), steps: recipe?.steps?.map((s: any) => ({ title: s.title, instruction: s.instruction })), searchTerms: recipe?.searchTerms?.map((s: any) => s.term) }).toLowerCase().replace(/[‌\u200c]/g, ' '); }
export async function loadRecipes() { const all = await prisma.recipe.findMany({ include: { ingredients: { orderBy: { order: 'asc' }, include: { ingredient: true } }, steps: { orderBy: { order: 'asc' } }, searchTerms: true, nutrition: true } }); const bySlug = new Map<string, any>(); for (const recipe of all) { const slug = parseJson(recipe.adminNote, {})?.slug; if (slug) bySlug.set(slug, recipe); } return rules.map((rule) => ({ rule, recipe: bySlug.get(rule.slug) })); }
function matches(blob: string, terms: string[]) { return terms.some((t) => blob.includes(t.toLowerCase())); }
export function evaluate(rule: Rule, recipe: any) { if (!recipe) return { status: 'KEEP_REVIEWONLY_WITH_EXACT_REASON', missing: ['recipe not found'], exactBlocker: 'رسپی با slug موردنظر پیدا نشد.' }; const blob = recipeBlob(recipe); const missing = rule.must.filter((group) => !matches(blob, group)).map((group) => group.join(' / ')); const status = missing.length === 0 ? 'RESTORE_PUBLIC_AS_IS' : 'KEEP_REVIEWONLY_WITH_EXACT_REASON'; return { status, missing, exactBlocker: status === 'RESTORE_PUBLIC_AS_IS' ? '' : `${rule.exactBlocker} Missing signals: ${missing.join(' ; ')}` }; }
export function rollbackEntry(recipe: any, slug: string) { return { recipeId: recipe.id, slug, titleFa: recipe.title, status: recipe.status, isPublic: recipe.isPublic, adminNote: recipe.adminNote, updatedAt: recipe.updatedAt }; }
export async function regressionStatus() { const [gamaj, qeymeh] = await Promise.all([prisma.recipe.findUnique({ where: { id: 'garnish_recipe_fa_104_7b4ced78' }, include: { ingredients: { include: { ingredient: true } }, searchTerms: true } }), prisma.recipe.findUnique({ where: { id: 'garnish_recipe_fa_170_44f0d2ad' }, include: { ingredients: { include: { ingredient: true } }, searchTerms: true } })]); const ingBlob = (r: any) => textValues([...(r?.ingredients ?? []).flatMap((ri: any) => [ri.name, ri.ingredient?.code, ri.ingredient?.nameFa, ri.ingredient?.nameEn]), ...(r?.searchTerms ?? []).map((t: any) => t.term)]).toLowerCase(); return { gamaj: !gamaj || /(^|[^a-z])egg([^a-z]|$)|egg_|_egg|تخم مرغ/.test(ingBlob(gamaj)) ? 'FAIL' : 'PASS', qeymeh: !qeymeh || /split_pea|split peas|لپه/.test(ingBlob(qeymeh)) ? 'FAIL' : 'PASS' }; }
export function patchGris(gris: any, marker: { label: string; ingredientId: string; code: string; note: string }) { const next = gris && typeof gris === 'object' ? JSON.parse(JSON.stringify(gris)) : {}; next.ingredients = Array.isArray(next.ingredients) ? next.ingredients : []; if (!textValues(next.ingredients).toLowerCase().includes(marker.code)) next.ingredients.push({ name: marker.label, ingredientId: marker.ingredientId, code: marker.code, role: marker.note, group: 'هویت اصلی', amount: 'به میزان دستور', buyTip: 'تازه و سالم انتخاب شود', substitution: 'حذف نشود؛ برای هویت غذا لازم است' }); next.steps = Array.isArray(next.steps) ? next.steps : []; if (!textValues(next.steps).toLowerCase().includes(marker.code)) next.steps.push({ order: next.steps.length + 1, title: `افزودن ${marker.label}`, instruction: `${marker.label} را برای ${marker.note} وارد دستور کنید.`, usesIngredientIds: [marker.ingredientId] }); return next; }
